channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=25.0.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - dataclasses==0.6
  - numpy==1.26.2
  - psutil==5.9.6
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - uuid==1.30
name: mlflow-env
